package com.orwlw.comm;

public class DBfinal {
	public static final String SQL_IMAGE_ERRINFO = "CREATE TABLE \"T_IMAGE_ERRINFO\" (\"F_Id\" TEXT PRIMARY KEY  UNIQUE  NOT NULL, \"F_PATH\" VARCHAR, \"F_ImageName\" VARCHAR, \"F_ImageType\" VARCHAR, \"F_CustomCode\" VARCHAR, \"F_DateTime\" VARCHAR,\"F_user\" VARCHAR,\"F_REMARK\" TEXT,\"F_LAT\" VARCHAR,\"F_LON\" VARCHAR)";
	public static final String SQL_IMAGE_TYPE = "CREATE TABLE \"T_IMAGE_TYPE\" (\"F_KEY_CODE\" TEXT , \"F_KEY_VALUE\" VARCHAR)";
	public static final String SQL_COMM_USED = "CREATE TABLE \"T_COMM_USED\" (\"F_COMM_CODE\" TEXT )";
	public static final String SQL_SCM_CATEGORY = "CREATE TABLE \"T_SCM_CATEGORY\" (\"F_COMM_CATEGORY_CODE\" VARCHAR,\"F_COMM_CATEGORY\" VARCHAR,\"F_PARENT_CODE\" VARCHAR )";
	public static final String SQL_Device_info = "CREATE TABLE \"T_Device_info\" (\"ID\" VARCHAR,\"IMEI\" VARCHAR,\"UID\" VARCHAR, \"DATETIME\" VARCHAR, \"LON\" VARCHAR, \"LAT\" VARCHAR, \"cid\" VARCHAR, \"lac\" VARCHAR, \"sysid\" VARCHAR, \"PhoneType\" VARCHAR, \"SPEED\" VARCHAR, \"mcc\" VARCHAR, \"mnc\" VARCHAR, \"neiborstring\" VARCHAR)";
	public static final String SQL_LOCATION_info="CREATE TABLE \"T_lOCATION_info\" (\"ID\" VARCHAR,\"IMEI\" VARCHAR,\"UID\" VARCHAR, \"DATETIME\" VARCHAR, \"LON\" VARCHAR, \"LAT\" VARCHAR, \"FLAG\" VARCHAR)";
	public static final String SQL_Custom_info = "CREATE TABLE \"T_Custom_info\" (\"F_CONTACT_PERSON\" VARCHAR,\"F_CUSTOM_CODE\" VARCHAR,\"F_CUSTOM_NAME\" VARCHAR, \"F_CO_ADDRESS\" VARCHAR,\"F_CONTACT_TEL\" VARCHAR, \"F_LON\" VARCHAR, \"F_LAT\" VARCHAR)";
	public static final String SQL_LOCAL_ORDER = "CREATE TABLE \"T_LOCAL_ORDER\" (\"F_CUSTOM_CODE\" VARCHAR,\"F_COMM_CODE\" VARCHAR,\"F_COMM_NAME\" VARCHAR, \"F_NUM1\" VARCHAR,\"F_NUM2\" VARCHAR,\"F_DATE\" VARCHAR)";
	public static final String SQL_EXCHAGNE_COMMS = "CREATE TABLE \"T_EXCHAGNE_COMMS\" (\"F_CUSTOM_CODE\" VARCHAR,\"F_COMM_CODE\" VARCHAR,\"F_COMM_NAME\" VARCHAR, \"F_NUM1\" VARCHAR,\"F_NUM2\" VARCHAR,\"F_REASON\" VARCHAR,\"F_REASON_ID\" VARCHAR,\"F_TYPE\" VARCHAR)";
	public static final String SQL_BACK_COMMS = "CREATE TABLE \"T_BACK_COMMS\" (\"F_CUSTOM_CODE\" VARCHAR,\"F_COMM_CODE\" VARCHAR,\"F_COMM_NAME\" VARCHAR, \"F_NUM1\" VARCHAR,\"F_NUM2\" VARCHAR,\"F_REASON\" VARCHAR,\"F_REASON_ID\" VARCHAR)";
	public static final String SQL_ENUM = "CREATE TABLE \"T_ENUM\" (\"F_KEY_CODE\" VARCHAR,\"F_KEY_VALUE\" VARCHAR,\"F_KEY_TYPE\" VARCHAR)";
}
